node {
    agent any
    
    def mvnHome  

    stages {
        stage('Prepare') {
            steps {
                git url: 'git@github.com:Salaam-Daris/migration-devops-ci.git',branch:'develop'
                mvnHome = tool 'mvn'
            }
        }
            
        stage('Build') {
            steps {
                if(isUnix()){
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
                }
                else{
                bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
                }
            }
        }
        
        stage('Unit Test') {
            steps {
            junit '**/target/surefire-reports/Test-*.xml'
            archive 'target/*.jar'
            }
        }
        
         stage('Integration Test') {
            steps {
                if(isUnix()){
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean verify"
                }
                else{
                bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean verify/)
                }
            }
        }
    }
}
    

